version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 1337:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-#i7#up#=wlht5bjo!seu5+70)$o%+f$tbxsvw^!#@s(5s(%k-z
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]